

name: CI 
#We can specify which GitHub events will trigger a CI Build
on: push 
#Now define a single job build (or more)
jobs: 
build:
#We can also specifiy the OS to run tests on
runs-on:ubuntu-latest
#a job is a seq of tests
steps: 
#Check out repos and python
#Name is a label
name: CHeckout Repository 
uses: actions/checkout@v2
name: Set Up Python 3.9
uses: actions/setup-python@v2
with: python-version: "3.9"
name: Install Python dependencies
run: | python -m pip install --upgrade pip
pip install -r packagelist.txt
name: Test with Pytest
run: | python -m pytest --cov=inflammation.models tests/test_models.py
